spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketingsystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: 2084220263@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: riljyyrkllxxijjg
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password:
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
mybatis:
  type-aliases-package: com.jie.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

#阿里云 msg
aliyun:
  send-msg:
    accessKeyId:  LTAI5tMnNaownHDXsf5hq3iL
    accessKeySecret:  M0AxVhX8aJ7l2IiW3ZqBeKyzqO9Cxv
    SignName:  阿里云短信测试
    TemplateCode:  SMS_154950909
#    SignName:  验证码短信
#    TemplateCode:  SMS_279961611


server:
  port: 8081
  compression:
    enabled: true

#日志
#logging:
#  level:
#    root: DEBUG
#    com.example.demo: INFO



